### ISSUE TITLE
如何实现clearfix

### ISSUE THREAD

**Issue by ReinerLau1** [ReinerLau1/Blog#110]
# 作用

清除浮动带来的影响

# 代码

```css
  .clearfix:after {
    content: "";
    display: table;
    clear: both;
  }
```
