### ISSUE TITLE
两栏布局的实现

### ISSUE THREAD

**Issue by ReinerLau1** [ReinerLau1/Blog#249]
# 概念

左边一栏宽度固定，右边一栏宽度自适应

**Comment by ReinerLau1** [comment]
# 实现一

- 将左边元素宽度设置为固定大小`200px`，并且设置向左浮动
- 将右边元素的`margin-left`设置为`200px`，宽度设置为`auto`

```css
.outer {
  height: 100px;
}
.left {
  float: left;
  width: 200px;
  background: tomato;
}
.right {
  margin-left: 200px;
  width: auto;
  background: gold;
}
```

**Comment by ReinerLau1** [comment]
# 实现二

- 左侧元素设置固定大小，并左浮动
- 右侧元素设置`overflow: hidden`，触发BFC
- BFC的区域不会与浮动元素发生重叠

```css
.left{
     width: 100px;
     height: 200px;
     background: red;
     float: left;
 }
 .right{
     height: 300px;
     background: blue;
     overflow: hidden;
 }
```

**Comment by ReinerLau1** [comment]
# 实现三

- 利用`flex`布局
- 将左边元素设置为固定宽度
- 将右边的元素设置为`flex:1`

```css
.outer {
  display: flex;
  height: 100px;
}
.left {
  width: 200px;
  background: tomato;
}
.right {
  flex: 1;
  background: gold;
}
```

**Comment by ReinerLau1** [comment]
# 实现四

- 将父级元素设置为相对定位
- 左边元素设置为`absolute`定位并且固定宽度`200px`
- 将右边元素的`margin-left`的值设置为`200px`

```css
.outer {
  position: relative;
  height: 100px;
}
.left {
  position: absolute;
  width: 200px;
  height: 100px;
  background: tomato;
}
.right {
  margin-left: 200px;
  background: gold;
}
```

**Comment by ReinerLau1** [comment]
# 实现五

- 将父级元素设置为相对定位
- 左边元素设置为固定宽度`200px`
- 右边元素设置为绝对定位，`left`定位在`200px`
- 其余方向定位为0

```css
.outer {
  position: relative;
  height: 100px;
}
.left {
  width: 200px;
  background: tomato;
}
.right {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 200px;
  background: gold;
}
```
