### ISSUE TITLE
三栏布局的实现

### ISSUE THREAD

**Issue by ReinerLau1** [ReinerLau1/Blog#250]
# 概念
左右两栏宽度固定，中间自适应的布局

**Comment by ReinerLau1** [comment]
# 实现一

- 左右两栏设置为绝对定位
- 中间设置左右对应大小的`margin`值

```css
.outer {
  position: relative;
  height: 100px;
}

.left {
  position: absolute;
  width: 100px;
  height: 100px;
  background: tomato;
}

.right {
  position: absolute;
  top: 0;
  right: 0;
  width: 200px;
  height: 100px;
  background: gold;
}

.center {
  margin-left: 100px;
  margin-right: 200px;
  height: 100px;
  background: lightgreen;
}
```

**Comment by ReinerLau1** [comment]
# 实现二

- `flex`布局
- 左右两栏设置固定大小
- 中间一栏设置为`flex:1`

```css
.outer {
  display: flex;
  height: 100px;
}

.left {
  width: 100px;
  background: tomato;
}

.right {
  width: 100px;
  background: gold;
}

.center {
  flex: 1;
  background: lightgreen;
}
```

**Comment by ReinerLau1** [comment]
# 实现三

- 左右两栏设置固定大小，并设置对应方向的浮动
- 中间一栏设置左右两个方向的`margin`值
- 中间一栏必须放到最后

```css
.outer {
  height: 100px;
}

.left {
  float: left;
  width: 100px;
  height: 100px;
  background: tomato;
}

.right {
  float: right;
  width: 200px;
  height: 100px;
  background: gold;
}

.center {
  height: 100px;
  margin-left: 100px;
  margin-right: 200px;
  background: lightgreen;
}
```

**Comment by ReinerLau1** [comment]
# 圣杯布局

- 父级元素设置左右的 padding
- 三列均设置向左浮动
- 中间一列放在最前面，宽度设置为父级元素的宽度
- 设置 margin 负值将其移动到上一行
- 利用相对定位，定位到两边

```css
.outer {
  height: 100px;
  padding-left: 100px;
  padding-right: 200px;
}

.left {
  position: relative;
  left: -100px;

  float: left;
  margin-left: -100%;

  width: 100px;
  height: 100px;
  background: tomato;
}

.right {
  position: relative;
  left: 200px;

  float: right;
  margin-left: -200px;

  width: 200px;
  height: 100px;
  background: gold;
}

.center {
  float: left;

  width: 100%;
  height: 100px;
  background: lightgreen;
}
```

**Comment by ReinerLau1** [comment]
# 双飞翼布局

- 相对于圣杯布局来说，左右位置的保留是通过中间列的 margin 值来实现的

```css
.outer {
  height: 100px;
}

.left {
  float: left;
  margin-left: -100%;

  width: 100px;
  height: 100px;
  background: tomato;
}

.right {
  float: left;
  margin-left: -200px;

  width: 200px;
  height: 100px;
  background: gold;
}

.wrapper {
  float: left;

  width: 100%;
  height: 100px;
  background: lightgreen;
}

.center {
  margin-left: 100px;
  margin-right: 200px;
  height: 100px;
}
```
