### ISSUE TITLE
水平垂直居中的实现

### ISSUE THREAD

**Issue by ReinerLau1** [ReinerLau1/Blog#251]
# 实现一

- 利用绝对定位，先将元素的左上角通过`top:50%`和`left:50%`定位到页面的中心
- 通过`translate`来调整元素的中心点到页面的中心
- 需要考虑浏览器兼容问题

```css
.parent {
    position: relative;
}

.child {
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%,-50%);
}
```

**Comment by ReinerLau1** [comment]
# 实现二

- 利用绝对定位，设置四个方向的值都为 0
- 并将`margin`设置为`auto`
- 适用于盒子有宽高的情况

```css
.parent {
    position: relative;
}

.child {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    margin: auto;
}
```

**Comment by ReinerLau1** [comment]
# 实现三

- 利用绝对定位，先将元素的左上角通过`top:50%`和`left:50%`定位到页面的中心
- 通过`margin`负值来调整元素的中心点到页面的中心
- 适用于盒子宽高已知的情况

```css
.parent {
    position: relative;
}

.child {
    position: absolute;
    top: 50%;
    left: 50%;
    margin-top: -50px;     /* 自身 height 的一半 */
    margin-left: -50px;    /* 自身 width 的一半 */
}
```

**Comment by ReinerLau1** [comment]
# 实现四

- 使用`flex`布局
- 通过`align-items:center`和`justify-content:center`设置容器的垂直和水平方向上为居中对齐
- 要考虑兼容的问题

```css
.parent {
    display: flex;
    justify-content:center;
    align-items:center;
}
```
- 如果父元素设置了`flex`布局，只需要给子元素加上·margin:auto`，就可以实现垂直居中布局

```css
.parent{
    display:flex;
}
.child{
    margin: auto;
}
```
