### ISSUE TITLE
使用 clear 属性清除浮动的原理

### ISSUE THREAD

**Issue by ReinerLau1** [ReinerLau1/Blog#256]
# 语法

```css
clear:none|left|right|both
```

**Comment by ReinerLau1** [comment]
# 原理

- 元素盒子的边不能和**前面的**浮动元素相邻
- 对元素设置`clear`属性是为了避免浮动元素对该元素的影响，而不是清除掉浮动
- `clear`属性只有块级元素才有效的
- 凡是`clear:left`或者`clear:right`起作用的地方，一定可以使用`clear:both`替换

**Comment by ReinerLau1** [comment]
# 使用

- 一般使用伪元素的方式清除浮动
- 而`::after`等伪元素默认都是内联水平

```css
.clear::after{
  content:'';
  display: block;
  clear:both;
}
```
