### ISSUE TITLE
实现一个三角形

### ISSUE THREAD

**Issue by ReinerLau1** [ReinerLau1/Blog#262]
# 原理

- CSS 绘制三角形主要用到的是`border`属性
- 实际上，border 属性是由三角形组成的

```css
div {
    width: 0;
    height: 0;
    border: 100px solid;
    border-color: orange blue red green;
}
```
![image](https://user-images.githubusercontent.com/25604088/150257795-de8d3402-43d0-4ad1-b5e8-3b5bc7ed6f75.png)

**Comment by ReinerLau1** [comment]
# 向下的三角形

```css
div {
    width: 0;
    height: 0;
    border-top: 50px solid red;
    border-right: 50px solid transparent;
    border-left: 50px solid transparent;
}
```
![image](https://user-images.githubusercontent.com/25604088/150258384-8fa72abe-2670-4ed0-85f1-3c847488d83c.png)

**Comment by ReinerLau1** [comment]
# 向上的三角形

```css
div {
    width: 0;
    height: 0;
    border-bottom: 50px solid red;
    border-right: 50px solid transparent;
    border-left: 50px solid transparent;
}
```
![image](https://user-images.githubusercontent.com/25604088/150258851-9a83e943-c27a-49f8-a082-4d21a00a4730.png)

**Comment by ReinerLau1** [comment]
# 向右的三角形

```css
div {
    width: 0;
    height: 0;
    border-left: 50px solid red;
    border-top: 50px solid transparent;
    border-bottom: 50px solid transparent;
}
```
![image](https://user-images.githubusercontent.com/25604088/150259310-4922d371-0eb1-4047-9eb6-adb2f566517e.png)

**Comment by ReinerLau1** [comment]
# 向左的三角形

```css
div {
    width: 0;
    height: 0;
    border-right: 50px solid red;
    border-top: 50px solid transparent;
    border-bottom: 50px solid transparent;
}
```
![image](https://user-images.githubusercontent.com/25604088/150259943-9f3e01b1-64dc-4608-997e-8ef7ffa7d308.png)

**Comment by ReinerLau1** [comment]
# 斜三角形

```css
div {
    width: 0;
    height: 0;
    border-top: 100px solid red;
    border-right: 100px solid red;
}
```

![image](https://user-images.githubusercontent.com/25604088/150260263-7b7ab707-b8b1-4f05-a81d-4f3cf4cf1caa.png)
