### ISSUE TITLE
实现一个扇形

### ISSUE THREAD

**Issue by ReinerLau1** [ReinerLau1/Blog#263]
# 原理

实现扇形的思路和三角形基本一致，就是多了一个圆角的样式

**Comment by ReinerLau1** [comment]
# 实现

```css
div{
    border: 100px solid transparent;
    width: 0;
    height: 0;
    border-radius: 100px;
    border-top-color: red;
}
```
![image](https://user-images.githubusercontent.com/25604088/150260905-216c5049-9215-4063-ac47-4e7f6ae9be5f.png)
