### ISSUE TITLE
实现一个宽高自适应的正方形

### ISSUE THREAD

**Issue by ReinerLau1** [ReinerLau1/Blog#264]
# 实现一

利用`vw`来实现

```css
.square {
  width: 10%;
  height: 10vw;
  background: tomato;
}
```

**Comment by ReinerLau1** [comment]
# 实现二

利用元素的`margin/padding`百分比是相对父元素`width`的性质来实现

```css
.square {
  width: 20%;
  height: 0;
  padding-top: 20%;
  background: orange;
}
```

**Comment by ReinerLau1** [comment]
# 实现三

利用子元素的`margin-top`的值来实现

```css
.square {
  width: 30%;
  overflow: hidden;
  background: yellow;
}
.square::after {
  content: '';
  display: block;
  margin-top: 100%;
}
```
