### ISSUE TITLE
伪元素和伪类的区别和作用

### ISSUE THREAD

**Issue by ReinerLau1** [ReinerLau1/Blog#56]
# 伪元素

- 在内容元素的前后插入额外的元素或者样式，
- 不在文档中生成，只会在外部显示

```css
p::before {content:"第一章：";}
p::after {content:"Hot!";}
p::first-line {background:red;}
p::first-letter {font-size:30px;}
```

**Comment by ReinerLau1** [comment]
# 伪类
- 在元素选择器上通过特殊的类名添加样式
- 不会新增元素

```css
a:hover {color: #FF00FF}
p:first-child {color: red}
```
